# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy PHP app to Azure Web App - ryu-test-appgw-apps

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer validate --no-check-publish && composer install --prefer-dist --no-progress

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: php-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: php-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'ryu-test-appgw-apps'
          slot-name: 'Production'
          publish-profile: '<publishData><publishProfile profileName="ryu-test-appgw-apps - Web Deploy" publishMethod="MSDeploy" publishUrl="ryu-test-appgw-apps.scm.azurewebsites.net:443" msdeploySite="ryu-test-appgw-apps" userName="$ryu-test-appgw-apps" userPWD="ZPadaCJa901AmgHHmaNlKDL4BSvij70WaC6LlYuQGsciZwJvlpq3igPR7dJi" destinationAppUrl="https://ryu-test-appgw-apps.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>'
          package: .
          use-private-link: true
          private-link-id: '/subscriptions/fcd48547-0c99-4366-a479-8d186594356c/resourceGroups/hoshino-test/providers/Microsoft.Network/privateEndpoints/ryutestappservicepe'
          private-dns-zone-resource-group: 'hoshino-test'
          private-dns-zone-name: 'privatelink.azurewebsites.net'
          private-dns-zone-relative-record-set-name: 'ryu-test-appgw-apps' 